### ISSUE TITLE
pykmip-server shuts down on client connect (vCenter Server 6.5)

### ISSUE THREAD

**Issue by thakala** [OpenKMIP/PyKMIP#209]
I am having issues with pykmip-server shutting down on client connect, client is VMware vCenter Server 6.5.

Below is server.log contents from pykmip-server start to vCenter Server 6.5 connect. I have full certificate trusts configured for client and server.

> 2016-11-27 01:33:54,959 - kmip.server.config - INFO - Loading server configuration settings from: /etc/pykmip/server.conf
2016-11-27 01:33:54,974 - kmip.server.engine - INFO - Loading user-defined operation policy files from: /etc/pykmip/policies
2016-11-27 01:33:54,975 - kmip.server.engine - INFO - Loading user_defined operation policies from file: /etc/pykmip/policies/policy.json
2016-11-27 01:33:54,976 - kmip.server - INFO - Starting server socket handler.
2016-11-27 01:33:54,978 - kmip.server - INFO - Server successfully bound socket handler to 0.0.0.0:5696
2016-11-27 01:33:54,978 - kmip.server - INFO - Starting connection service...
2016-11-27 01:34:08,006 - kmip.server - WARNING - Error detected while establishing new connection.
2016-11-27 01:34:08,007 - kmip.server - ERROR - [SSL: NO_CERTIFICATE_RETURNED] no certificate returned (_ssl.c:765)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/services/server/server.py", line 297, in serve connection, address = self._socket.accept()
  File "/usr/lib64/python2.7/ssl.py", line 862, in accept server_side=True)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 588, in __init__ self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 810, in do_handshake self._sslobj.do_handshake()
SSLError: [SSL: NO_CERTIFICATE_RETURNED] no certificate returned (_ssl.c:765)
2016-11-27 01:34:08,008 - kmip.server - INFO - Stopping connection service.
2016-11-27 01:34:08,008 - kmip.server - INFO - Cleaning up remaining connection threads.
2016-11-27 01:34:08,009 - kmip.server - INFO - Shutting down server socket handler.

**Comment by thakala** [comment]
This issue was caused by self-signed certificate on client side. Connection was established successfully once I replaced client certificate on vCenter Server with trusted CA signed one.
