### ISSUE TITLE
kmip.server NotImplementedError with VMware vCenter Server 6.5

### ISSUE THREAD

**Issue by thakala** [OpenKMIP/PyKMIP#211]
I am having trouble issuing certificates to VMware vCenter Server 6.5. Certificate requests trigger an "NotImplementedError" on pykmip-server.

Below is contents of server.log during certificate request

> 2016-11-27 13:03:47,353 - kmip.server - INFO - Receiving incoming connection from: 192.168.78.10:40412
2016-11-27 13:03:47,354 - kmip.server - INFO - Dedicating session 00000007 to 192.168.x.x:40412
2016-11-27 13:03:47,355 - kmip.server.session.00000007 - INFO - Starting session: 00000007
2016-11-27 13:03:47,358 - kmip.server.session.00000007 - INFO - Session client identity: kmipClient20161127094708
2016-11-27 13:03:47,360 - kmip.server.engine - INFO - Received request at time: 2016-11-27 11:03:47
2016-11-27 13:03:47,361 - kmip.server.engine - INFO - Processing operation: DiscoverVersions
2016-11-27 13:03:47,364 - kmip.server.session.00000007 - INFO - Session client identity: kmipClient20161127094708
2016-11-27 13:03:47,367 - kmip.server.engine - INFO - Received request at time: 2016-11-27 11:03:47
2016-11-27 13:03:47,368 - kmip.server.engine - INFO - Processing operation: Create
2016-11-27 13:03:47,368 - kmip.server.engine.cryptography - INFO - Generating a AES symmetric key with length: 256
2016-11-27 13:03:47,379 - kmip.server.engine - INFO - Created a SymmetricKey with ID: 13
2016-11-27 13:03:47,381 - kmip.server.session.00000007 - INFO - Stopping session: 00000007
2016-11-27 13:03:47,454 - kmip.server - INFO - Receiving incoming connection from: 192.168.78.10:40416
2016-11-27 13:03:47,454 - kmip.server - INFO - Dedicating session 00000008 to 192.168.x.x:40416
2016-11-27 13:03:47,455 - kmip.server.session.00000008 - INFO - Starting session: 00000008
2016-11-27 13:03:47,457 - kmip.server.session.00000008 - INFO - Session client identity: kmipClient20161127094708
2016-11-27 13:03:47,459 - kmip.server.engine - INFO - Received request at time: 2016-11-27 11:03:47
2016-11-27 13:03:47,460 - kmip.server.engine - INFO - Processing operation: DiscoverVersions
2016-11-27 13:03:47,463 - kmip.server.session.00000008 - INFO - Session client identity: kmipClient20161127094708
2016-11-27 13:03:47,465 - kmip.server.engine - INFO - Received request at time: 2016-11-27 11:03:47
2016-11-27 13:03:47,466 - kmip.server.engine - INFO - Processing operation: Get
2016-11-27 13:03:47,471 - kmip.server.engine - INFO - Getting a SymmetricKey with ID: 13
2016-11-27 13:03:47,474 - kmip.server.session.00000008 - INFO - Session client identity: kmipClient20161127094708
2016-11-27 13:03:47,475 - kmip.server.session.00000008 - WARNING - Failure parsing request message.
2016-11-27 13:03:47,475 - kmip.server.session.00000008 - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/services/server/session.py", line 150, in _handle_message_loop
    request.read(request_data)
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/core/messages/messages.py", line 354, in read
    batch_item.read(istream)
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/core/messages/messages.py", line 203, in read
    self.operation.value)
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/core/factories/payloads/__init__.py", line 44, in create
    return self._create_get_attributes_payload()
  File "/usr/lib/python2.7/site-packages/PyKMIP-0.5.0-py2.7.egg/kmip/core/factories/payloads/__init__.py", line 117, in _create_get_attributes_payload
    raise NotImplementedError()
NotImplementedError
2016-11-27 13:03:47,477 - kmip.server.session.00000008 - INFO - Stopping session: 00000008

Below is logs from vCenter Server

> 2016-11-27T11:08:28.434Z info vpxd[7F2212164700] [Originator@6876 sub=CryptoManager opID=EditEncryptionModeViewMediator-apply-14823-ngc-93] Generated new cryptoKeyId 14/KMS for the host [vim.HostSystem:host-109,esxi.lan.local]
2016-11-27T11:08:28.525Z error vpxd[7F2212164700] [Originator@6876 sub=CryptoManagerKmipWrapper opID=EditEncryptionModeViewMediator-apply-14823-ngc-93] Get, Attributes, Id=%s, Names=State failed on key 14, Error parsing request message. See server logs for more information.
2016-11-27T11:08:28.525Z warning vpxd[7F2212164700] [Originator@6876 sub=CryptoManager opID=EditEncryptionModeViewMediator-apply-14823-ngc-93] Cannot get key 14 from KMS server kms1, reason: Error parsing request message. See server logs for more information.
2016-11-27T11:08:28.526Z info vpxd[7F2212164700] [Originator@6876 sub=vpxLro opID=EditEncryptionModeViewMediator-apply-14823-ngc-93] [VpxLRO] -- FINISH task-536
2016-11-27T11:08:28.526Z info vpxd[7F2212164700] [Originator@6876 sub=Default opID=EditEncryptionModeViewMediator-apply-14823-ngc-93] [VpxLRO] -- ERROR task-536 -- host-109 -- vim.HostSystem.configureCryptoKey: vmodl.RuntimeFault:
--> Result:
--> (vmodl.RuntimeFault) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = (vmodl.LocalizableMessage) [
-->       (vmodl.LocalizableMessage) {
-->          key = "com.vmware.vim.vpxd.encryption.keyNotFound",
-->          arg = (vmodl.KeyAnyValue) [
-->             (vmodl.KeyAnyValue) {
-->                key = "key",
-->                value = "14/KMS"
-->             }
-->          ],
-->          message = <unset>
-->       }
-->    ]
-->    msg = ""
--> }
--> Args:
-->
--> Arg keyId:
-->

**Comment by PeterHamilton** [comment]
It looks like the server is failing when you send it a `GetAttributes` request, which makes sense since it doesn't support the `GetAttributes` operation yet. Fortunately, I'm pushing code today that will begin introducing `GetAttributes` support across the client and server. This work should be finished over the next few days so this should resolve itself naturally once that merges.

**Comment by thakala** [comment]
Excellent news, thank you!
