### ISSUE TITLE
Support to VM Encryption in vSphere 6.5

### ISSUE THREAD

**Issue by a2940uw** [OpenKMIP/PyKMIP#234]
Hello All, happy to see vmware now support to VM encryption with KMIP protocol, only PyKMIP is free solution at this moment, hope to see more article to show to setup and manage PyKMIP in this topic and see vmware contribute more code to pykimp

**Comment by PeterHamilton** [comment]
The PyKMIP GitHub [wiki](https://github.com/OpenKMIP/PyKMIP/wiki) has information on how to install, setup, and use PyKMIP.

**Comment by jseadragon** [comment]
What kind of help do you need with this @PeterHamilton? If docs are needed, I may be able to devote a little time. Granted, I didn't have much issue getting pykmip running, but people new to python may have a bit of a learning curve.

**Comment by PeterHamilton** [comment]
I don't think I need anything at the moment. I'm waiting to see if @a2940uw provides more details on what is needed. However, if you want to review the wiki or the README, I'm happy to review any updates or changes you think are appropriate.

**Comment by sbingner** [comment]
I'm not sure what else may be needed, but it needs to have _create_get_attributes_payload implemented.  I set up a test and tried it out.  Below is the full log:

`2016-12-16 04:28:53,996 - kmip.server - INFO - Receiving incoming connection from: 192.168.0.90:52954
2016-12-16 04:28:53,997 - kmip.server - INFO - Dedicating session 00000007 to 10.0.0.9:52954
2016-12-16 04:28:53,997 - kmip.server.session.00000007 - INFO - Starting session: 00000007
2016-12-16 04:28:54,000 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,000 - kmip.server.engine - INFO - Processing operation: DiscoverVersions
2016-12-16 04:28:54,021 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,021 - kmip.server.engine - INFO - Processing operation: Create
2016-12-16 04:28:54,022 - kmip.server.engine.cryptography - INFO - Generating a AES symmetric key with length: 256
2016-12-16 04:28:54,043 - kmip.server.engine - INFO - Created a SymmetricKey with ID: 1
2016-12-16 04:28:54,044 - kmip.server.session.00000007 - INFO - Stopping session: 00000007
2016-12-16 04:28:54,149 - kmip.server - INFO - Receiving incoming connection from: 10.0.0.9:52956
2016-12-16 04:28:54,150 - kmip.server - INFO - Dedicating session 00000008 to 10.0.0.9:52956
2016-12-16 04:28:54,150 - kmip.server.session.00000008 - INFO - Starting session: 00000008
2016-12-16 04:28:54,151 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,152 - kmip.server.engine - INFO - Processing operation: DiscoverVersions
2016-12-16 04:28:54,154 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,154 - kmip.server.engine - INFO - Processing operation: Create
2016-12-16 04:28:54,154 - kmip.server.engine.cryptography - INFO - Generating a AES symmetric key with length: 256
2016-12-16 04:28:54,162 - kmip.server.engine - INFO - Created a SymmetricKey with ID: 2
2016-12-16 04:28:54,163 - kmip.server.session.00000008 - INFO - Stopping session: 00000008
2016-12-16 04:28:54,261 - kmip.server - INFO - Receiving incoming connection from: 10.0.0.9:52958
2016-12-16 04:28:54,261 - kmip.server - INFO - Dedicating session 00000009 to 10.0.0.9:52958
2016-12-16 04:28:54,262 - kmip.server.session.00000009 - INFO - Starting session: 00000009
2016-12-16 04:28:54,264 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,264 - kmip.server.engine - INFO - Processing operation: DiscoverVersions
2016-12-16 04:28:54,267 - kmip.server.engine - INFO - Received request at time: 2016-12-16 09:28:54
2016-12-16 04:28:54,267 - kmip.server.engine - INFO - Processing operation: Get
2016-12-16 04:28:54,270 - kmip.server.engine - INFO - Getting a SymmetricKey with ID: 2
2016-12-16 04:28:54,271 - kmip.server.session.00000009 - WARNING - Failure parsing request message.
2016-12-16 04:28:54,272 - kmip.server.session.00000009 - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kmip/services/server/session.py", line 93, in _handle_message_loop
    certificate_data,
  File "/usr/lib/python2.7/site-packages/kmip/core/messages/messages.py", line 354, in read
    batch_item.read(istream)
  File "/usr/lib/python2.7/site-packages/kmip/core/messages/messages.py", line 203, in read
    self.operation.value)
  File "/usr/lib/python2.7/site-packages/kmip/core/factories/payloads/__init__.py", line 44, in create
    return self._create_get_attributes_payload()
  File "/usr/lib/python2.7/site-packages/kmip/core/factories/payloads/__init__.py", line 117, in _create_get_attributes_payload
    def _create_rekey_payload(self):
NotImplementedError
2016-12-16 04:28:54,273 - kmip.server.session.00000009 - INFO - Stopping session: 00000009`

**Comment by PeterHamilton** [comment]
The `Rekey` operation is not currently supported by PyKMIP, though I'd be happy to add it in. I may have some time over the holidays to work on it. I'll post an update once I get started.

Also, thanks for posting this info. You may want to file a separate issue for `Rekey` support, since this is a rather generic and open-ended issue thread.

**Comment by sbingner** [comment]
Looking at this again and I'm a little confused.  It says it errored out at _create_rekey_payload in the source view from the backtrace but the backtrace function actually says it is _create_get_attributes_payload... I think maybe it was actually _create_get_attributes_payload?

**Comment by sbingner** [comment]
OK, so that was just an error in the __init__.py which I fixed with the changes below:
`diff --git a/kmip/core/factories/payloads/__init__.py b/kmip/core/factories/payloads/__init__.py
index 30a4a2f..4e3fe98 100644
--- a/kmip/core/factories/payloads/__init__.py
+++ b/kmip/core/factories/payloads/__init__.py
@@ -132,15 +132,6 @@ class PayloadFactory():
     def _create_check_payload(self):
         raise NotImplementedError()
 
-    def _create_get_payload(self):
-        raise NotImplementedError()
-
-    def _create_get_attributes_payload(self):
-        raise NotImplementedError()
-
-    def _create_get_attribute_list_payload(self):
-        raise NotImplementedError()
-
     def _create_add_attribute_payload(self):
         raise NotImplementedError()`

Now I get a new error... will work on it more soon:

> 2016-12-17 19:24:18,832 - kmip.server - INFO - Receiving incoming connection from: 10.0.0.9:54972
2016-12-17 19:24:18,833 - kmip.server - INFO - Dedicating session 00000002 to 10.0.0.9:54972
2016-12-17 19:24:18,833 - kmip.server.session.00000002 - INFO - Starting session: 00000002
2016-12-17 19:24:18,834 - kmip.server.session.00000002 - WARNING - Failure parsing request message.
2016-12-17 19:24:18,834 - kmip.server.session.00000002 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kmip/services/server/session.py", line 149, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python2.7/site-packages/kmip/services/server/session.py", line 111, in _get_client_identity
    "The extended key usage extension is missing from the client "
PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2016-12-17 19:24:18,837 - kmip.server.session.00000002 - WARNING - Failure parsing request message.
2016-12-17 19:24:18,837 - kmip.server.session.00000002 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kmip/services/server/session.py", line 149, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python2.7/site-packages/kmip/services/server/session.py", line 111, in _get_client_identity
    "The extended key usage extension is missing from the client "
PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2016-12-17 19:24:18,838 - kmip.server.session.00000002 - INFO - Stopping session: 00000002

**Comment by PeterHamilton** [comment]
Yep, you're right, I read the wrong line in that original traceback dump. The version of the server you're using doesn't support `GetAttributes`. Which version are you using? The latest version (0.6.0) does support `GetAttributes`, so upgrading to the latest version may be what you need to do.

For the second traceback you provided, this relates to the client authentication the server conducts to determine who is connecting to the server (and which user ID to associate with newly created objects). You'll need to use a client certificate that has the extended key usage extension defined, specifically marked to indicate that the client certificate is intended for use in client authentication. See [Identity & Ownership](https://github.com/OpenKMIP/PyKMIP/blob/master/README.rst#identity--ownership) in the README and/or [Certificates](https://github.com/OpenKMIP/PyKMIP/wiki/Certificates) in the wiki for more information.

**Comment by sbingner** [comment]
The attachment of a diff seemed to fail horribly so I made a [pull request](https://github.com/OpenKMIP/PyKMIP/pull/237) for the changes I made to make _create_get_attributes_payload  work properly.  I'm working on the client cert half now :)

**Comment by sbingner** [comment]
After updating my PyKMIP to 0.6.0 and fixing the extended usage of client authentication to the vSphere certificate I can verify that it successfully encrypted a VM.  I'm guessing that if /tmp/pykmip.database disappears that VM will be unusable after powering off.  Will report back with full findings.

**Comment by sbingner** [comment]
1.  Able to power machine on and off without vCenter communication with PyKMIP
2.  When I clone a VM it uses the same encryption keys as the source VM and does not contact PyKMIP - but it seems to possibly use a different seed or something? encryption.keySafe and encryption.data change in the vmx file but reference the same key from PyKMIP.  PyKMIP is not queried during the clone operation.
3.  Encrypting a new VM or re-encrypting a VM that has had encryption removed does get a new key from PyKMIP
4.  vmx file is not encrypted nor is VM.vmdk file (they are text config files and say where to get the encryption data for the other files).  The  VM-flat.vmdk (data) and VM..nvram is encrypted
5.  vMotion of a VM between hosts does not contact PyKMIP - it seems that the key is either transferred over the encrypted vMotion or cached on vCenter.
6.  Rebooting vCenter also does not clear the cache of encryption keys... 


It is difficult to make ESX query PyKMIP regarding an encrypted but opened VM, looks like it would only do it after a reboot but I don't want to bring my whole server down for a reboot.  In any case, everything seems to be working great as far as PyKMIP goes.

**Comment by PeterHamilton** [comment]
Glad to hear that 0.6.0 is working for you. You are correct, if `/tmp/pykmip.database` is deleted the keys will be gone. You can back the file up yourself if you need persistence. I am planning on eventually expanding the SQLAlchemy backends we support, including adding a SQLite option letting you set where the backing file lives. One day I'd like to have the server use an actual persistent database.

Just to be clear, right now the PyKMIP server is really only meant for testing and demonstrations. It's not meant to stand up to production workloads. As I add security and robustness features I'm hoping it eventually becomes a viable option, but that's a ways off.

**Comment by sbingner** [comment]
One issue that I encountered is that if `/tmp/pykmip.database` still exists from 0.5.0, nothing works because when it tries to commit a new key it gets the error:
`2016-12-18 02:15:34,123 - kmip.server.engine - ERROR - (sqlite3.OperationalError) table managed_objects has no column named operation_policy_name [SQL: u'INSERT INTO managed_objects (object_type, class_type, value, name_index, operation_policy_name, owner) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: (2, 'SymmetricKey', <read-only buffer for 0x7f8c601c9b28, size -1, offset 0 at 0x7f8c601cdf70>, 1, 'default', u'kmipClientCLIENTID')]`

This was of course fixed by removing `/tmp/pykmip.database` but it took me a while to track the file down :)

**Comment by PeterHamilton** [comment]
Yep, that error occurs whenever underlying data model changes are made (in your case it was the addition of `operation_policy_name` support). I'll update the README to specifically call out the backing file. I also need to setup an FAQ in the wiki and include an entry for this error, so others don't have to go through the same forensics you did.

**Comment by esstokes1** [comment]
I'm trying to do the same - can someone explain to me about "fixing the extended usage of client authentication to the vSphere certificate"?  Thanks

**Comment by PeterHamilton** [comment]
That statement refers to the extended key usage extension of the client certificate itself. If the client certificate does not have this extension, it cannot be used for client authentication. See the PyKMIP README/wiki or RFC 5280 for more information on the extension.

You'd need to ask @sbingner directly for specific details on the fix he used.

Feel free to file another issue on this if your case is different (I should've closed this one months ago).

**Comment by santosh253** [comment]
**I am getting following error while provide certificate and key file in vcenter** 
2017-04-17 16:21:50,275 - kmip.server.session.00000005 - WARNING - Failure parsing request message.
2017-04-17 16:21:50,275 - kmip.server.session.00000005 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/session.py", line 149, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/session.py", line 111, in _get_client_identity
    "The extended key usage extension is missing from the client "
PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2017-04-17 16:21:50,293 - kmip.server.session.00000005 - WARNING - Failure parsing request message.
2017-04-17 16:21:50,294 - kmip.server.session.00000005 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/session.py", line 149, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/local/lib/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/session.py", line 111, in _get_client_identity
    "The extended key usage extension is missing from the client "
PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2017-04-17 16:21:50,296 - kmip.server.session.00000005 - INFO - Stopping session: 00000005

**If I havn't provide those files, I am getting below error**

2017-04-17 16:28:39,552 - kmip.server - ERROR - [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/server.py", line 303, in serve
    connection, address = self._socket.accept()
  File "/usr/lib/python2.7/ssl.py", line 461, in accept
    raise e
SSLError: [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
2017-04-17 16:28:39,556 - kmip.server - WARNING - Error detected while establishing new connection.
2017-04-17 16:28:39,556 - kmip.server - ERROR - [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/server.py", line 303, in serve
    connection, address = self._socket.accept()
  File "/usr/lib/python2.7/ssl.py", line 461, in accept
    raise e
SSLError: [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
2017-04-17 16:28:39,792 - kmip.server - WARNING - Error detected while establishing new connection.
2017-04-17 16:28:39,792 - kmip.server - ERROR - [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/server.py", line 303, in serve
    connection, address = self._socket.accept()
  File "/usr/lib/python2.7/ssl.py", line 461, in accept
    raise e
SSLError: [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
2017-04-17 16:28:40,304 - kmip.server - WARNING - Error detected while establishing new connection.
2017-04-17 16:28:40,304 - kmip.server - ERROR - [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.6.0-py2.7.egg/kmip/services/server/server.py", line 303, in serve
    connection, address = self._socket.accept()
  File "/usr/lib/python2.7/ssl.py", line 461, in accept
    raise e
SSLError: [Errno 1] _ssl.c:510: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned

Please provide me help

**Comment by PeterHamilton** [comment]
This is the same error discussed above with @esstokes1 and @sbingner. Your client certificate **must** have the extended key usage extension with client authentication set to be used for client authentication with PyKMIP.

According to the KMIP specification:

> Conformant KMIP servers SHALL use the identity derived from the channel mutual authentication to determine the client identity...

Since KMIP servers/clients must use TLS to conform with the KMIP specification, the identity must be derived from the client's certificate.

For more information on client authentication with certificates, see RFC 5280. If you are creating your certificates yourself, you will need to use OpenSSL (or something equivalent) to include that extension during the certificate creation process. If you are obtaining your certificates from a third-party, you will need to have them add the extension for you.

I'm going to close this thread, since it's become an umbrella issue for various errors regarding vSphere/vCenter integration. Please file a more specific issue for this topic if you need more assistance.

Thanks!
Peter
