### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

### ISSUE THREAD

**Issue by digiisoft** [OpenKMIP/PyKMIP#402]
Hello,

I must not understand the sequence for using a self signed certificate to talk to pyKMIP.  I generated a certificate for pyKIMP and I have tried every option in VMWare but still I keep getting this error...

`Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/server.py", line 358, in serve
    connection, address = self._socket.accept()
  File "/usr/lib64/python3.4/ssl.py", line 859, in accept
    server_side=True)
  File "/usr/lib64/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
2018-03-22 13:07:02,050 - kmip.server - WARNING - Error detected while establishing new connection.
2018-03-22 13:07:02,050 - kmip.server - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)`

Any help is appreciated.

Thanks,

Chris

**Comment by PeterHamilton** [comment]
@digiisoft Thanks for filing this issue. Working with SSL certificates is usually one of the trouble spots new users run into when working with PyKMIP. I have a couple of questions that should help guide us towards solving this problem.

1. How are you using and configuring PyKMIP in VMware?
2. How did you generate the certificates for the PyKMIP client and server?

**Comment by digiisoft** [comment]
Well it looks like I was finally able to get past the last issue by using 2 certificates generated on the server that contains pyKMIP.   Now I am getting this error...
```2018-03-22 14:29:09,944 - kmip.server - INFO - Receiving incoming connection from: 192.168.192.17:47984
2018-03-22 14:29:09,944 - kmip.server - INFO - Dedicating session 00000018 to 192.168.192.17:47984
2018-03-22 14:29:09,946 - kmip.server.session.00000018 - INFO - Starting session: 00000018
2018-03-22 14:29:09,946 - kmip.server.session.00000018 - INFO - Stopping session: 00000018
2018-03-22 14:29:10,055 - kmip.server - INFO - Receiving incoming connection from: 192.168.192.17:47986
2018-03-22 14:29:10,055 - kmip.server - INFO - Dedicating session 00000019 to 192.168.192.17:47986
2018-03-22 14:29:10,056 - kmip.server.session.00000019 - INFO - Starting session: 00000019
2018-03-22 14:29:10,056 - kmip.server.session.00000019 - DEBUG - Session cipher selected: ('AES256-SHA', 'TLSv1/SSLv3', 256)
2018-03-22 14:29:10,058 - kmip.server.session.00000019 - WARNING - Failure parsing request message.
2018-03-22 14:29:10,058 - kmip.server.session.00000019 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 118, in _get_client_identity
    x509.oid.ExtensionOID.EXTENDED_KEY_USAGE
  File "/usr/lib/python3.4/site-packages/cryptography-2.2.1-py3.4-linux-x86_64.egg/cryptography/x509/extensions.py", line 81, in get_extension_for_oid
    raise ExtensionNotFound("No {0} extension was found".format(oid), oid)
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)> extension was found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 173, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 122, in _get_client_identity
    "The extended key usage extension is missing from the "
kmip.core.exceptions.PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2018-03-22 14:29:10,061 - kmip.server.session.00000019 - DEBUG - Session cipher selected: ('AES256-SHA', 'TLSv1/SSLv3', 256)
2018-03-22 14:29:10,062 - kmip.server.session.00000019 - WARNING - Failure parsing request message.
2018-03-22 14:29:10,062 - kmip.server.session.00000019 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 118, in _get_client_identity
    x509.oid.ExtensionOID.EXTENDED_KEY_USAGE
  File "/usr/lib/python3.4/site-packages/cryptography-2.2.1-py3.4-linux-x86_64.egg/cryptography/x509/extensions.py", line 81, in get_extension_for_oid
    raise ExtensionNotFound("No {0} extension was found".format(oid), oid)
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)> extension was found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 173, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 122, in _get_client_identity
    "The extended key usage extension is missing from the "
kmip.core.exceptions.PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2018-03-22 14:29:10,064 - kmip.server.session.00000019 - INFO - Stopping session: 00000019
2018-03-22 14:29:10,166 - kmip.server - INFO - Receiving incoming connection from: 192.168.192.17:47990
2018-03-22 14:29:10,167 - kmip.server - INFO - Dedicating session 00000020 to 192.168.192.17:47990
2018-03-22 14:29:10,168 - kmip.server.session.00000020 - INFO - Starting session: 00000020
2018-03-22 14:29:10,168 - kmip.server.session.00000020 - DEBUG - Session cipher selected: ('AES256-SHA', 'TLSv1/SSLv3', 256)
2018-03-22 14:29:10,169 - kmip.server.session.00000020 - WARNING - Failure parsing request message.
2018-03-22 14:29:10,169 - kmip.server.session.00000020 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 118, in _get_client_identity
    x509.oid.ExtensionOID.EXTENDED_KEY_USAGE
  File "/usr/lib/python3.4/site-packages/cryptography-2.2.1-py3.4-linux-x86_64.egg/cryptography/x509/extensions.py", line 81, in get_extension_for_oid
    raise ExtensionNotFound("No {0} extension was found".format(oid), oid)
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)> extension was found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 173, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 122, in _get_client_identity
    "The extended key usage extension is missing from the "
kmip.core.exceptions.PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2018-03-22 14:29:10,172 - kmip.server.session.00000020 - DEBUG - Session cipher selected: ('AES256-SHA', 'TLSv1/SSLv3', 256)
2018-03-22 14:29:10,173 - kmip.server.session.00000020 - WARNING - Failure parsing request message.
2018-03-22 14:29:10,173 - kmip.server.session.00000020 - ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 118, in _get_client_identity
    x509.oid.ExtensionOID.EXTENDED_KEY_USAGE
  File "/usr/lib/python3.4/site-packages/cryptography-2.2.1-py3.4-linux-x86_64.egg/cryptography/x509/extensions.py", line 81, in get_extension_for_oid
    raise ExtensionNotFound("No {0} extension was found".format(oid), oid)
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)> extension was found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 173, in _handle_message_loop
    client_identity = self._get_client_identity()
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.8.dev0-py3.4.egg/kmip/services/server/session.py", line 122, in _get_client_identity
    "The extended key usage extension is missing from the "
kmip.core.exceptions.PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
2018-03-22 14:29:10,175 - kmip.server.session.00000020 - INFO - Stopping session: 00000020```

**Comment by PeterHamilton** [comment]
That helps. These errors:
```
ERROR - The extended key usage extension is missing from the client certificate. Session client identity unavailable.
```
```
cryptography.x509.extensions.ExtensionNotFound: No <ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)> extension was found
```
```
kmip.core.exceptions.PermissionDenied: The extended key usage extension is missing from the client certificate. Session client identity unavailable.
```

indicate that your client certificate does not contain the X.509 ``extendedKeyUsage`` extension. That is one of the extensions that can be used to determine if your client certificate can be used to actually authenticate the client's identity (instead of just being used to secure the connection).

To **temporarily** get around this problem, you can set ``enable_tls_client_auth`` in the server configuration to ``False``. This will allow the server to skip the check for the ``extendedKeyUsage`` extension. For more information on this, see the [documentation](https://pykmip.readthedocs.io/en/latest/faq.html#how-does-the-pykmip-server-handle-client-identity-and-authentication).

If you're going to be using PyKMIP long term, I'd recommend regenerating your certificates to included the missing extension. That way, they are properly marked and follow the X.509 spec. Of course, many people don't bother so it's ultimately up to you.

**Comment by digiisoft** [comment]
Peter,

I added `extendedKeyUsage = clientAuth` to my openssl.cnf file and re-issued the certs and walah! 

Thanks for the help!

Chris

**Comment by PeterHamilton** [comment]
Excellent, I'm glad that fixed your problem. I'll go ahead and close this issue. Feel free to reach out again if you need any further help.
