### ISSUE TITLE
Crash in client after rekey operation

### ISSUE THREAD

**Issue by randombit** [OpenKMIP/PyKMIP#424]
Testing #422, my client crashes seemingly while parsing the response. The rekey request is formatted and sent to the server, but when the server replies, `NotImplementedError` is thrown by the client. Any ideas?

This is using git master ea7da73b4fb18a001e91c9509164532482aad055

I can include a hex encoding of the KMIP binary blob of the response if that is helpful.

Good news is we can successfully rekey now :) but having to catch `NotImplemented` and then using `locate` to find the new key id is not ideal.

```
Traceback (most recent call last):
  File "pykmip/pykmip_tests.py", line 795, in <module>
    sys.exit(main())
  File "pykmip/pykmip_tests.py", line 744, in main
    rekey_test(client)
  File "pykmip/pykmip_tests.py", line 101, in rekey_test
    new_id = client.rekey(key_id)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/pie/client.py", line 39, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/pie/client.py", line 467, in rekey
    template_attribute=template_attribute
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/services/kmip_client.py", line 340, in rekey
    response = self._send_and_receive_message(request)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/services/kmip_client.py", line 1550, in _send_and_receive_message
    response.read(data)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/core/messages/messages.py", line 385, in read
    batch_item.read(istream)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/core/messages/messages.py", line 291, in read
    expected = self.payload_factory.create(self.operation.value)
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/core/factories/payloads/__init__.py", line 30, in create
    return self._create_rekey_payload()
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/core/factories/payloads/__init__.py", line 118, in _create_rekey_payload
    raise NotImplementedError()
```

**Comment by PeterHamilton** [comment]
@randombit Doh, yeah, I know what the problem is. Give me a minute.

**Comment by PeterHamilton** [comment]
@randombit #425 should fix this. You'll hit the same error when trying to use ``Check`` as well. I'll have a patch up for that in a little bit.
