### ISSUE TITLE
Bug: race condition when upgrading six during integration test builds

### ISSUE THREAD

**Issue by PeterHamilton** [OpenKMIP/PyKMIP#435]
The latest patch adding new functional tests (#434) adds [SLUGS](https://github.com/OpenKMIP/SLUGS) as a dependency. SLUGS in turn requires six>=1.11.0 to avoid its own dependency issues (see https://github.com/OpenKMIP/SLUGS/issues/3). The default version of six on the Travis CI test nodes appears to be 1.10.0. The process of upgrading six from 1.10.0 to 1.11.0 periodically causes an install error (see below, taken from [here](https://travis-ci.org/OpenKMIP/PyKMIP/jobs/377296270)):

```
Successfully built slugs
Installing collected packages: six, more-itertools, backports.functools-lru-cache, cheroot, pytz, tempora, portend, cherrypy, slugs
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
    return self.__dep_map
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
    return self._pkg_info
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
    _Distribution.__init__(self, attrs)
  File "/opt/python/3.5.2/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/dist.py", line 389, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/six-1.10.0.dist-info/METADATA'


The command "pip install slugs" failed and exited with 2 during .
```
Determine why this occurs and fix it.

**Comment by PeterHamilton** [comment]
This appears to be a year old bug associated with newer versions of ``setuptools`` (see https://github.com/pypa/setuptools/issues/951). The forced reinstall of ``six`` occurs while ``pip`` is attempting to query package metadata; because ``six`` is temporarily missing, this triggers a fault. Given that this occurs sporadically, it does appear to be a true race condition between setup and pip.

The discussion thread above suggests pinning ``setuptools>=36.0.0`` may solve this problem, as that version avoids the race condition by coming with its own internal version of ``six``. I am unsure what the implications are if another, external version of ``six`` is installed or used alongside ``setuptools``.

**Comment by PeterHamilton** [comment]
Pinning ``setuptools>=36.0.0`` does not work. Instead, the solution used for https://github.com/OpenKMIP/SLUGS/issues/3 appears to work here. Specifically, updating ``.travis.yml`` to explicitly uninstall the default ``six`` installation and replace it with the required version removes the race condition:

```
install:
  # Pin six to >= 1.11.0 to avoid setuptools/pip race condition
  # For more info, see: https://github.com/OpenKMIP/PyKMIP/issues/435
  - pip uninstall -y six
  - pip install six>=1.11.0
  - pip install tox
  - pip install bandit
  - pip install codecov
  - pip install slugs
  - python setup.py install
```

Travis CI can now run all of the test routines across Python and platform versions without issue (see [here](https://travis-ci.org/OpenKMIP/PyKMIP/builds/377314890?utm_source=github_status&utm_medium=notification)).
