### ISSUE TITLE
Certificate Authority issues with selfsigned certs

### ISSUE THREAD

**Issue by FailedFace** [OpenKMIP/PyKMIP#444]
When I generate a set of certs, using the following tutorial: https://gist.github.com/mtigas/952344
I get this problem when i try to execute the client demo for key creation (https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/demos/pie/create.py):
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)

Why is my CA unknown? Shouldn't the fact that I used the same root to create the client and server certs mean it should be known?

BTW I'm incredibly new at this stuff, sorry for any oversights/ bad protocol. Please correct my behavior.

**Comment by PeterHamilton** [comment]
@FailedFace Thanks for filing this issue. I can't speak to the correctness of that tutorial. However, if you created the client and server certificates using the same root CA certificate, and specify that root CA certificate as the CA for both the client and server, you should not see an error. Double check that your client/server configuration files are filled out properly and that the client/server has access to the certificate files.

If this error persists, you can try using the ``bin/create_certificates.py`` script. It creates a predefined set of certificates that we use mostly for testing but they should work just as well with the demo scripts. If those certificates work, compare how they're built and defined with the certificates you're currently using. That may illuminate what's going wrong.

**Comment by FailedFace** [comment]
Thanks. Both the server and client are using the same CA. I think the gold is in your second paragraph. Using the "create-certificates" script. I ran that before and got a lot of certs back. Do you know which certs are used for the server and the shared CA? The Client certs are pretty obvious because of the names (Smith, Doe/etc).

**Comment by PeterHamilton** [comment]
The ``server_certificate.pem`` and ``server_key.pem`` files should be used for the server. The ``root_certificate.pem`` should be used for the CA for both the client and server. The remaining files are for different client users which are used to test different server features. I'd recommend sticking with the ``John Doe`` certificate; that one should work for all of the demo scripts.

**Comment by FailedFace** [comment]
Thanks, I'll give it a go. I'll report back.

**Comment by FailedFace** [comment]
Looks like I'm still having issues:
```
root@extkeystore:~/kmip# ./client.py  --algorithm=RSA --length=128
An error occurred while connecting to appliance 127.0.0.1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 131, in open
    self.proxy.open()
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 235, in open
    raise last_error
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 224, in open
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python3.5/ssl.py", line 1019, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.5/ssl.py", line 1010, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./client.py", line 51, in <module>
    config_file=opts.config_file
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 1573, in __enter__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 134, in open
    self.logger.exception("could not open client connection", e)
Message: 'could not open client connection'
Arguments: (SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)
Traceback (most recent call last):
  File "./client.py", line 51, in <module>
    config_file=opts.config_file
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 1573, in __enter__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 135, in open
    raise e
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 131, in open
    self.proxy.open()
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 235, in open
    raise last_error
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 224, in open
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python3.5/ssl.py", line 1019, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.5/ssl.py", line 1010, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

I'm using the python example from here: https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/demos/pie/create.py

Here is my server.conf:
```
[server]
hostname=127.0.0.1
port=5696
certificate_path=/root/kmip/server_certs/server_certificate.pem
key_path=/root/kmip/server_certs/server_key.pem
ca_path=/root/kmip/root_certificate.pem
auth_suite=Basic
policy_path=/root/kmip/
enable_tls_client_auth=True
tls_cipher_suites=
	TLS_RSA_WITH_AES_128_CBC_SHA256
	TLS_RSA_WITH_AES_256_CBC_SHA256
	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
logging_level=DEBUG
```
Here is my pykmip.conf:
```
[client]
hostname=127.0.0.1
port=5696
certificate_path=/root/kmip/client_certs/client_certificate_john_doe.pem
key_path=/root/kmip/client_certs/client_key_john_doe.pem
ca_path=/root/kmip/root_certificate.pem
cert_reqs=CERT_REQUIRED
ssl_version=PROTOCOL_SSLv23
do_handshake_on_connect=True
suppress_ragged_eofs=True
username=keyuser
password=tdc
```

**Comment by PeterHamilton** [comment]
Hmmm, that's odd. Are you running this on Ubuntu 18.04 by any chance?

**Comment by FailedFace** [comment]
Nope, 16.04

**Comment by FailedFace** [comment]
From /var/log/pykmip/server.log:
```
2018-06-21 01:41:03,970 - kmip.server.monitor - INFO - Starting up the operation policy file monitor.
2018-06-21 01:41:03,975 - kmip.server - INFO - Starting server socket handler.
2018-06-21 01:41:03,975 - kmip.server - DEBUG - Configured cipher suites: 3
2018-06-21 01:41:03,975 - kmip.server - DEBUG - TLS_RSA_WITH_AES_256_CBC_SHA256
2018-06-21 01:41:03,975 - kmip.server - DEBUG - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
2018-06-21 01:41:03,975 - kmip.server - DEBUG - TLS_RSA_WITH_AES_128_CBC_SHA256
2018-06-21 01:41:03,975 - kmip.server - DEBUG - Authentication suite ciphers to use: 12
2018-06-21 01:41:03,975 - kmip.server - DEBUG - AES128-SHA
2018-06-21 01:41:03,975 - kmip.server - DEBUG - DES-CBC3-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - AES256-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-DSS-DES-CBC3-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-RSA-DES-CBC3-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DH-DSS-AES128-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DH-RSA-AES128-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-DSS-AES128-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-RSA-AES128-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DH-RSA-AES256-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-DSS-AES256-SHA
2018-06-21 01:41:03,976 - kmip.server - DEBUG - DHE-RSA-AES256-SHA
2018-06-21 01:41:03,977 - kmip.server - INFO - Server successfully bound socket handler to 127.0.0.1:5696
2018-06-21 01:41:03,977 - kmip.server - INFO - Starting connection service...
2018-06-21 01:41:04,972 - kmip.server.monitor - INFO - Loading policies for file: /root/kmip/policy.json
2018-06-21 01:41:04,974 - kmip.server.monitor - INFO - Loading policy: example
2018-06-21 01:41:36,877 - kmip.server - WARNING - Error detected while establishing new connection.
2018-06-21 01:41:36,878 - kmip.server - ERROR - [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/server/server.py", line 410, in serve
    connection, address = self._socket.accept()
  File "/usr/lib/python3.5/ssl.py", line 1035, in accept
    server_side=True)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)
```
I don't see anything in syslog.

I wonder what versions of ssl packages you have. These are mine:
```
libgnutls-openssl27/now 3.4.10-4ubuntu1.4 amd64 [installed,local]
libssl1.0.0/xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
openssl/xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
```

Perhaps I did a bad when trying to fulfill dependencies for pykmip. Any advice on the installation selections for 16.04? I can install on another server for comparison purposes.

**Comment by PeterHamilton** [comment]
Here's what my current dev box (Ubuntu 16.04 LTS) has on it for SSL/TLS:
```
libgnutls-openssl27/xenial-updates,now 3.4.10-4ubuntu1.4 amd64 [installed]
libio-socket-ssl-perl/xenial,xenial,now 2.024-1 all [installed]
libnet-smtp-ssl-perl/xenial,xenial,now 1.03-1 all [installed]
libnet-ssleay-perl/xenial,now 1.72-1build1 amd64 [installed]
libssl-dev/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
libssl-doc/xenial-updates,xenial-updates,xenial-security,xenial-security,now 1.0.2g-1ubuntu4.12 all [installed]
libssl1.0.0/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
openssl/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
ssl-cert/xenial,xenial,now 1.0.37 all [installed]
```
```
libcurl3-gnutls/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.8 amd64 [installed]
libgnutls-openssl27/xenial-updates,now 3.4.10-4ubuntu1.4 amd64 [installed]
libgnutls30/xenial-updates,now 3.4.10-4ubuntu1.4 amd64 [installed]
libneon27-gnutls/xenial,now 0.30.1-3build1 amd64 [installed]
```
I doubt the Perl libraries are relevant here but ``libssl-dev`` might have some effect. Some minor Googling indicates that old versions of ``libneon`` can also cause SSL handshake issues. So maybe try updating/installing the latest versions of those packages?

**Comment by FailedFace** [comment]
I have updated those packages, but to no avail:
```
root@extkeystore:~/kmip# apt list --installed | grep -i "ssl\|tls\|neon"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcurl3-gnutls/xenial-security,now 7.47.0-1ubuntu2.8 amd64 [installed]
libgnutls-openssl27/now 3.4.10-4ubuntu1.4 amd64 [installed,local]
libgnutls30/now 3.4.10-4ubuntu1.4 amd64 [installed,local]
libio-socket-ssl-perl/xenial,xenial,now 2.024-1 all [installed]
libneon27/xenial,xenial,now 0.30.1-3build1 amd64 [installed]
libnet-smtp-ssl-perl/xenial,xenial,now 1.03-1 all [installed]
libnet-ssleay-perl/xenial,xenial,now 1.72-1build1 amd64 [installed,automatic]
libssl-dev/xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
libssl-doc/xenial-security,now 1.0.2g-1ubuntu4.12 all [installed,automatic]
libssl1.0.0/xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
openssl/xenial-security,now 1.0.2g-1ubuntu4.12 amd64 [installed]
ssl-cert/xenial,xenial,now 1.0.37 all [installed]
```
Seems to still be having some trouble.

**Comment by PeterHamilton** [comment]
I think I've got it. Update your client configuration file like so:

* ``certificate_path`` -> ``certfile``
* ``key_path`` -> ``keyfile``
* ``ca_path`` -> ``ca_certs``

The client and server use different names for the same parameters (an artifact of them being developed separately way back when). I've been meaning to migrate the client config towards the server naming scheme. If this fixes your problem, I'll add that to the top of my queue.

**Comment by FailedFace** [comment]
You are on the money!
```
root@extkeystore:~/kmip# ./client.py  --algorithm=RC4 --length=128
2018-06-22 00:48:45,092 - demo - INFO - Successfully created symmetric key with ID: 1
root@extkeystore:~/kmip#
```
Works great now. Thanks for remembering that difference in the files!

**Comment by PeterHamilton** [comment]
Awesome! Glad that fixed it. I'll close this issue for now and will make sure to update the client config before the next release.
