### ISSUE TITLE
Problems with connecting client to server across network

### ISSUE THREAD

**Issue by FailedFace** [OpenKMIP/PyKMIP#448]
Configuration file for the client doesn't seem to have the right information in it for changing the client to point to a different server location. It keeps trying to use 127.0.0.1 (localhost). 

Client Config:
```
[client]
hostname=10.25.105.15
port=5696
certfile=/root/kmip/client_certs/client_certificate_jane_doe.pem
keyfile=/root/kmip/client_certs/client_key_jane_doe.pem
ca_certs=/root/kmip/root_certificate.pem
cert_reqs=CERT_REQUIRED
ssl_version=PROTOCOL_SSLv23
do_handshake_on_connect=True
suppress_ragged_eofs=True
username=keyuser
password=keyuser
```

Attempt to connect to server using example: [Create.py](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/demos/pie/create.py)
```
root@ubuntu:~/kmip# ./client.py --algorithm=RC4 --length=128
An error occurred while connecting to appliance 127.0.0.1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kmip/pie/client.py", line 131, in open
    self.proxy.open()
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 235, in open
    raise last_error
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/kmip_client.py", line 224, in open
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python3.5/ssl.py", line 1019, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.5/ssl.py", line 1006, in _real_connect
    socket.connect(self, addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
...
```
"An error occurred while connecting to appliance 127.0.0.1"
Why is is trying to connect to local?

Is this a case of the wrong config parameter key name?

**Comment by PeterHamilton** [comment]
@FailedFace Yep, same issue as before. Use ``host`` instead of ``hostname``.

Check out the [client documentation](https://pykmip.readthedocs.io/en/latest/client.html) for more information.

**Comment by FailedFace** [comment]
Thanks!

**Comment by PeterHamilton** [comment]
@FailedFace No problem, glad it helped!
