### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by tstkenny** [OpenKMIP/PyKMIP#469]
Would somebody give me a hand on the below error?  I've been in google for whole day but no luck.  

I verified the certificate, private key and CA file and all are valid.  Someone elsewhere mentioned that this may be due to making https request to PyKMIP which is http only.. I have no clue about what it means.

2018-11-28 16:45:57,836 - kmip.server - INFO - Starting connection service...
2018-11-28 16:45:57,837 - kmip.server.monitor - INFO - Starting up the operation policy file monitor.
2018-11-28 16:45:58,839 - kmip.server.monitor - INFO - Loading policies for file: /etc/pykmip/policies/policy.json
2018-11-28 16:45:58,841 - kmip.server.monitor - INFO - Loading policy: example
2018-11-28 16:46:02,701 - kmip.server - WARNING - Error detected while establishing new connection.
2018-11-28 16:46:02,702 - kmip.server - ERROR - [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/kmip/services/server/server.py", line 410, in serve
    connection, address = self._socket.accept()
  File "/usr/lib64/python2.7/ssl.py", line 883, in accept
    server_side=True)
  File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:579)

Thanks a million!

**Comment by PeterHamilton** [comment]
Hi @tstkenny, thanks for filing this issue. This is likely a problem with the specific SSL/TLS protocol version you are using to connect to the server.

To debug this, we'll need several pieces of information. First, what version of Python are you using to run the PyKMIP server? If you are using Python to run a KMIP client, like one of the PyKMIP demo scripts, what version of Python are you using?

Next, what SSL/TLS version are you using with your KMIP client? Like the above, if you're using one of the PyKMIP demo scripts, this would be the value of the `ssl_version` parameter or configuration file setting used by the client.

Finally, in your PyKMIP server configuration file, what is the value of the `auth_suite` setting?

**Comment by PeterHamilton** [comment]
Hi @tstkenny, I just wanted to check on the status of this issue. Were you able to resolve the problem? If so, what was the solution?

If I don't hear back from you, I'll go ahead and close this issue in a few days.

**Comment by PeterHamilton** [comment]
Hi @tstkenny, since I haven't heard back from you I'm going to close this issue. Feel free to comment on it in the future if you still need help. I'll reopen it then.

**Comment by thomasleveil** [comment]
for others stumbling onto this, this is the kind of error which arises when you make a HTTP call on a HTTPS endpoint
