### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by whalehub** [OpenKMIP/PyKMIP#488]
I installed PyKMIP from master earlier today and ran it with the following `server.conf` config file:

```
[server]
hostname=127.0.0.1
port=5696
certificate_path=/etc/pykmip/certs/server_cert.pem
key_path=/etc/pykmip/certs/server_private_key.pem
ca_path=/etc/pykmip/certs/server_ca_cert.pem
auth_suite=TLS1.2
enable_tls_client_auth=True
database_path=/etc/pykmip/db/pykmip.database
```

In the terminal, I'm seeing the following output:
```
root@debian:~# pykmip-server
Process PolicyDirectoryMonitor-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.9.dev0-py2.7.egg/kmip/services/server/monitor.py", line 145, in run
    self.scan_policies()
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.9.dev0-py2.7.egg/kmip/services/server/monitor.py", line 82, in scan_policies
    policy_files = get_json_files(self.policy_directory)
  File "/usr/local/lib/python2.7/dist-packages/PyKMIP-0.9.dev0-py2.7.egg/kmip/services/server/monitor.py", line 29, in get_json_files
    f = [os.path.join(p, x) for x in os.listdir(p) if x.endswith(".json")]
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Any idea what could be causing this issue?

**Comment by PeterHamilton** [comment]
Hi @whalehub, it looks like you're missing the `policy_path` setting from your configuration file. See the server configuration [docs](https://pykmip.readthedocs.io/en/latest/server.html#configuration) for more info.

**Comment by whalehub** [comment]
@PeterHamilton That was it, thanks!
