### ISSUE TITLE
Fix revocation_message tag.

### ISSUE THREAD

**Issue by KBassford** [OpenKMIP/PyKMIP#546]
The revocation_message (in the revoke method) is defined as a string, but when that string is used (filled in), then the KMIP server will error and reject the message.

example:
Client side ...
```
revoke(
    revocation_reason=RevocationReasonCode.UNSPECIFIED,
    uid=32,
    revocation_message='revoke function',
    compromise_occurrence_date=None
)

Traceback (most recent call last):
  File "./src/local-gitlab.com/gkbassf/go-pykmip-wrapper/kmiprevoke/kmip_revoke.py", line 119, in <module>
    main(args)
  File "./src/local-gitlab.com/gkbassf/go-pykmip-wrapper/kmiprevoke/kmip_revoke.py", line 87, in main
    compromise_occurrence_date=cod
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 39, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 1007, in revoke
    raise exceptions.KmipOperationFailure(status, reason, message)
kmip.pie.exceptions.KmipOperationFailure: OPERATION_FAILED: INVALID_MESSAGE - Error parsing request message. See server logs for more information.

```
Sever Log ...
```
2019-06-07 11:14:00,458 - kmip.server - INFO - Receiving incoming connection from: 172.24.200.224:48532
2019-06-07 11:14:00,459 - kmip.server - INFO - Dedicating session 00000250 to 172.24.200.224:48532
2019-06-07 11:14:00,459 - kmip.server.session.00000250 - INFO - Starting session: 00000250
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - Possible session ciphers: 24
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES128-GCM-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,466 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES256-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES256-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES256-SHA256', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES128-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES128-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES128-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES256-SHA', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,467 - kmip.server.session.00000250 - DEBUG - ('ECDHE-ECDSA-AES128-SHA', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('ECDHE-RSA-AES128-SHA', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('DHE-RSA-AES128-SHA', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES256-GCM-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES128-GCM-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES256-SHA256', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES128-SHA256', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES256-SHA', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - ('AES128-SHA', 'TLSv1/SSLv3', 128)
2019-06-07 11:14:00,468 - kmip.server.session.00000250 - DEBUG - Session cipher selected: ('ECDHE-RSA-AES256-SHA384', 'TLSv1/SSLv3', 256)
2019-06-07 11:14:00,470 - kmip.server.session.00000250 - WARNING - Failure parsing request message.
2019-06-07 11:14:00,470 - kmip.server.session.00000250 - ERROR - Tried to read Base.tag: expected 0x420000, received 0x420080
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kmip/services/server/session.py", line 166, in _handle_message_loop
    request.read(request_data, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/messages/messages.py", line 473, in read
    batch_item.read(istream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/messages/messages.py", line 301, in read
    self.request_payload.read(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/messages/payloads/revoke.py", line 84, in read
    self.revocation_reason.read(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/objects.py", line 3594, in read
    self.revocation_message.read(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/primitives.py", line 865, in read
    super(TextString, self).read(istream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/primitives.py", line 105, in read
    self.read_tag(istream)
  File "/usr/local/lib/python3.5/dist-packages/kmip/core/primitives.py", line 60, in read_tag
    hex(tag)
kmip.core.exceptions.ReadValueError: Tried to read Base.tag: expected 0x420000, received 0x420080
2019-06-07 11:14:00,472 - kmip.server.session.00000250 - INFO - Stopping session: 00000250

```
The tag comparason (second to last ine in the Server Log) fails.  Leaving the message off, or setting it to None, works fine.

**Comment by PeterHamilton** [comment]
I've reproduced this bug and identified a fix. I'll have a patch up in a few minutes.
