### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by MIennaco** [OpenKMIP/PyKMIP#616]
I'm using PyKmip for security testing. Occasionally the PyKmip server can't find the requested keys.

In the server.log I'm finding the (unhelpful) error messages:

```
kmip.server.session.00000247 - ERROR - [Errno 1] _ssl.c:1429: error:140940F6:SSL routines:SSL3_READ_BYTES:unknown alert type
```

```
kmip.server.session.00000247 - ERROR - [Errno 1] _ssl.c:1429: error:140944B0:SSL routines:SSL3_READ_BYTES:reason(1200)
```

Is there any way to improve these error messages? I realize that they appear to be from OpenSSL but can they be caught and wrapped with information about what PyKMIP was trying to do?

**Comment by PeterHamilton** [comment]
Hi @MIennaco, thanks for posting this issue. Can you provide more of the stack trace from this error? It should hopefully be in the logs. With that I can narrow down where the error gets thrown from in the server and should be able to wrap it with additional contextual information.

**Comment by MIennaco** [comment]
Here is an example of the unknown alert type:

2020-01-16 12:55:39,534 - kmip.server.session.00000212 - INFO - Failure handling message loop
2020-01-16 12:55:39,535 - kmip.server.session.00000212 - ERROR - [Errno 1] _ssl.c:1429: error:140940F6:SSL routines:SSL3_READ_BYTES:unknown alert type
Traceback (most recent call last):
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 102, in run
    self._handle_message_loop()
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 114, in _handle_message_loop
    request_data = self._receive_request()
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 302, in _receive_request
    header = self._receive_bytes(8)
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 316, in _receive_bytes
    min(message_size - bytes_received, self._max_buffer_size)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:140940F6:SSL routines:SSL3_READ_BYTES:unknown alert type

**Comment by MIennaco** [comment]
Here is a :reason(number) example:

2020-01-16 12:54:06,519 - kmip.server.session.00000150 - INFO - Failure handling message loop
2020-01-16 12:54:06,519 - kmip.server.session.00000150 - ERROR - [Errno 1] _ssl.c:1429: error:1409444D:SSL routines:SSL3_READ_BYTES:reason(1101)
Traceback (most recent call last):
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 102, in run
    self._handle_message_loop()
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 114, in _handle_message_loop
    request_data = self._receive_request()
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 302, in _receive_request
    header = self._receive_bytes(8)
  File "/tmp/tmp.6QlX8MRxRA/local/lib/python2.7/site-packages/kmip/services/server/session.py", line 316, in _receive_bytes
    min(message_size - bytes_received, self._max_buffer_size)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:1409444D:SSL routines:SSL3_READ_BYTES:reason(1101)

The server.log.1 file contains "unknown alert type" failures, and server.log.2 contains both.
[server.log.1.txt](https://github.com/OpenKMIP/PyKMIP/files/4074150/server.log.1.txt)
[server.log.2.txt](https://github.com/OpenKMIP/PyKMIP/files/4074153/server.log.2.txt)

**Comment by Amn04** [comment]
Any progress in this?
