### ISSUE TITLE
Cannot run KMIP server 

### ISSUE THREAD

**Issue by maximbalin** [OpenKMIP/PyKMIP#622]
Hi all,

I try to run KMIP after installation but get error:

root@KMIP:/home/kmip/pykmip/bin# python3.7 run_server.py -h
Traceback (most recent call last):
  File "run_server.py", line 18, in <module>
    from kmip.services.server import server
ModuleNotFoundError: No module named 'kmip'

**Comment by PeterHamilton** [comment]
Hi @maximbalin, thanks for filing this issue. First, how did you install PyKMIP? Is it installed under Python 3.7 or is it installed under a different version of Python?

**Comment by maximbalin** [comment]
I installed kmip under 2.7 but had other error:
root@KMIP:/home/kmip/pykmip/bin# python run_server.py
Traceback (most recent call last):
  File "run_server.py", line 22, in <module>
    server.main()
AttributeError: 'module' object has no attribute 'main'

It is why i installed 3.7 version

**Comment by PeterHamilton** [comment]
Which version of PyKMIP are you using?

When I run the same above command, this is what I see:

```
$ python run_server.py -h
Usage: run_server.py [options]

Run the PyKMIP software server.

Options:
  -h, --help            show this help message and exit
...
```

Did you install PyKMIP using `pip` or did you install it using `python setup.py install`?

**Comment by maximbalin** [comment]
I installed the latest version.
I used pip to install

**Comment by PeterHamilton** [comment]
Please run the following command and let me know what the output from it is:

```
$ pip list | grep PyKMIP
```

**Comment by KBassford** [comment]
I have to agree.  I'm setting up another test server and due to operational constraints I cannot put the config file parameter  (pykmip-server --config_path=/config/kmip.server/server.conf) in the default location.  It looks like it has been commented out in the server.py.

**Comment by AlexanderKAdams** [comment]
Did anyone make any progress on this? I have attempted install today using Python 3.7, and have the same issue. 

```
ubuntu@kms:/usr/local$ python3 PyKMIP/bin/run_server.py -h
Traceback (most recent call last):
  File "PyKMIP/bin/run_server.py", line 18, in <module>
    from kmip.services.server import server
ModuleNotFoundError: No module named 'kmip'
ubuntu@kms:/usr/local$ pip3 list | grep PyKMIP
PyKMIP                 0.11.0.dev1
```

**Comment by mealan** [comment]
sudo ln -s /usr/bin/python3 /usr/bin/python helped for me

**Comment by rzerr** [comment]
In my case, this issue happen when trying to perform installation from different directory.

You need to go to PyKMIP folder and perform python setup.py install, afterward the issue is fixed.

**Comment by IAmDaiNguyen** [comment]
In my case, Because I installed PKMIP in the wrong directory : 
Fix :
be sure you are in the PyKMIP directory ( usually /usr/local/PyKMIP ), then
Run command : python3 /usr/local/PyKMIP/setup.py install

**Comment by angelocook** [comment]
ok, another project that has died and no support.  I have rebuild a VM 3 times from scratch follow the steps to the letter and the same error that others had:

  File "PyKMIP/bin/run_server.py", line 18, in <module>
    from kmip.services.server import server
ModuleNotFoundError: No module named 'kmip'

**Comment by dariuszduszynski** [comment]
Hi, I hve tested and work for me. 
I've made this start server python script:
--------
import logging
logging.basicConfig(level=logging.DEBUG)

from kmip.services.server import KmipServer

if __name__ == "__main__":
    server = KmipServer(config_path='/etc/pykmip/pykmip-server.conf')
    print("[*] Strting server...")
    server.start()
    print("[*] Server started...")

    try:
        server.serve()
    except KeyboardInterrupt:
        print("\n[*] Stopping server...")
        server.stop()

**Comment by angelocook** [comment]
I have tried to follow these instructions 
   https://blog.masterwayz.nl/setting-up-a-free-kms-server-for-vcenter-with-pykmip-with-database/ 
which I discovered needs a few modifications, like 'chown <$username>: -R /etc/ssl/private' before the 'openssl req' line.
and the adding of 'cd /usr/local/PyKMIP' before the 'python3 ' line - I know it's in the parentheses but really.
 
the next thing is that python has depreciated many of the methods the PyMKIP code uses, and I am still a newby with python although my C, C# and C++ skills help and hinder. I am learning.

I have tried various Ubuntu versions (16, 18 and 22) and each were a challenge to install just the OS on VMware VM

I resorted to Copilot for step by step instructions to install the required dependencies before setting up PyKMIP, it even that told me to use old commands 'pip install cryptography flask sqlalchemy' which python complained about an older version but would not update.

I know this Ubuntu is developers dream land, but this instability to install these cool projects to play with seems to be just attempts and no one actually has them fully functioning and when they do the OS or python changes something and BOOM!
