### ISSUE TITLE
PyKMIP not working yet with Ubuntu 20.0.4/python3.7

### ISSUE THREAD

**Issue by jzendle** [OpenKMIP/PyKMIP#631]
Hi

I'm having trouble getting client/server running properly with self signed certs. I've tried several ways to generate keys with no luck. Any help would be greatly appreciated.

Details below.

1.  From the server log upon client connect:

2020-08-03 15:53:23,510 - kmip.server.monitor - INFO - Loading policies for file: ./policy.json
2020-08-03 15:53:23,521 - kmip.server.monitor - INFO - Loading policy: example
2020-08-03 15:53:57,089 - kmip.server - INFO - Stopping connection service.
2020-08-03 15:53:57,089 - kmip.server - INFO - Cleaning up remaining connection threads.
2020-08-03 15:53:57,090 - kmip.server - INFO - Shutting down server socket handler.
2020-08-03 15:53:57,329 - kmip.server.monitor - INFO - Stopping the operation policy file monitor.
2020-08-03 15:54:06,246 - kmip.server.config - INFO - Loading server configuration settings from: server.conf
2020-08-03 15:54:06,267 - kmip.server.monitor - INFO - Starting up the operation policy file monitor.
2020-08-03 15:54:06,277 - kmip.server - INFO - Starting server socket handler.
2020-08-03 15:54:06,278 - kmip.server - DEBUG - Configured cipher suites: 3
2020-08-03 15:54:06,278 - kmip.server - DEBUG - TLS_RSA_WITH_AES_128_CBC_SHA256
2020-08-03 15:54:06,278 - kmip.server - DEBUG - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
2020-08-03 15:54:06,278 - kmip.server - DEBUG - TLS_RSA_WITH_AES_256_CBC_SHA256
2020-08-03 15:54:06,278 - kmip.server - DEBUG - Authentication suite ciphers to use: 12
2020-08-03 15:54:06,278 - kmip.server - DEBUG - AES128-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DES-CBC3-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - AES256-SHA    
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DHE-DSS-DES-CBC3-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DHE-RSA-DES-CBC3-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DH-DSS-AES128-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DH-RSA-AES128-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DHE-DSS-AES128-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DHE-RSA-AES128-SHA
2020-08-03 15:54:06,278 - kmip.server - DEBUG - DH-RSA-AES256-SHA
2020-08-03 15:54:06,279 - kmip.server - DEBUG - DHE-DSS-AES256-SHA
2020-08-03 15:54:06,279 - kmip.server - DEBUG - DHE-RSA-AES256-SHA
2020-08-03 15:54:06,281 - kmip.server - INFO - Server successfully bound socket handler to 127.0.0.1:5696  
2020-08-03 15:54:06,281 - kmip.server - INFO - Starting connection service...
2020-08-03 15:54:07,279 - kmip.server.monitor - INFO - Loading policies for file: ./policy.json
2020-08-03 15:54:07,285 - kmip.server.monitor - INFO - Loading policy: example
2020-08-03 15:54:24,826 - kmip.server - INFO - Receiving incoming connection from: 127.0.0.1:51514
2020-08-03 15:54:24,827 - kmip.server - INFO - Dedicating session 00000001 to 127.0.0.1:51514
2020-08-03 15:54:24,827 - kmip.server.session.00000001 - INFO - Starting session: 00000001
2020-08-03 15:54:24,827 - kmip.server.session.00000001 - INFO - Failure running TLS handshake
**2020-08-03 15:54:24,827 - kmip.server.session.00000001 - ERROR - [SSL] internal error (_ssl.c:1091)
Traceback (most recent call last):
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/services/server/session.py", line 102, in run
    self._connection.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()**    
ssl.SSLError: [SSL] internal error (_ssl.c:1091)
2020-08-03 15:54:24,828 - kmip.server.session.00000001 - INFO - Stopping session: 00000001

2. Server config:

[server]
hostname=127.0.0.1
port=5696
key_path=../openssl/certs/yoursite.org.key
certificate_path=../openssl/certs/yoursite.org.crt
ca_path=         ../openssl/certs/yoursite.org.crt
auth_suite=Basic
policy_path=.
enable_tls_client_auth=True
tls_cipher_suites=
    TLS_RSA_WITH_AES_128_CBC_SHA256
    TLS_RSA_WITH_AES_256_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
logging_level=DEBUG
database_path=/tmp/pykmip.db

3. Environment:

(venv37) jzendle@fred:~/Projects/kmip/server$ python --version
Python 3.7.8
(venv37) jzendle@fred:~/Projects/kmip/server$ pip list
Package      Version
------------ ---------
certifi      2020.6.20
cffi         1.14.1
chardet      3.0.4
cryptography 3.0
enum-compat  0.0.3
enum34       1.1.10
idna         2.10
pip          20.2
pycparser    2.20
PyKMIP       0.10.0
requests     2.24.0
setuptools   49.2.1
six          1.15.0
SQLAlchemy   1.3.18
urllib3      1.25.10
wheel        0.34.2
(venv37) jzendle@fred:~/Projects/kmip/server$ openssl version
OpenSSL 1.1.1f  31 Mar 2020

(venv37) jzendle@fred:~/Projects/kmip$ uname -a
Linux fred 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(venv37) jzendle@fred:~/Projects/kmip$

**Comment by KBassford** [comment]
Are you using the script included (PyKMIP/bin/create_certificates.py)?  The server and client still cannot use openssl generated certs (#566).

**Comment by jzendle** [comment]
Thanks for quick response. I did try certs from create_certificates.py. Still having issues.

Wondering what your test linux environment is? OS version, etc.

As a sanity check:
1) clean VM (Ubuntu 20.4) with updates
2) clean python3.7.8 from deadsnakes (3.8.2 is default python for Ubuntu 20.4)
3) clean 3.7.8 virtual python env
3) certificates built with create_certificates.py

server.conf:

[server]
hostname=127.0.0.1
port=5696
certificate_path=/home/jzendle/pykmip/certs/server_certificate.pem
key_path=/home/jzendle/pykmip/certs/server_key.pem
ca_path=/home/jzendle/pykmip/certs/root_certificate.pem
auth_suite=Basic
policy_path=/home/jzendle/pykmip/policies
enable_tls_client_auth=False
tls_cipher_suites=
    EXAMPLE_CIPHER_SUITE_1
    EXAMPLE_CIPHER_SUITE_2
    EXAMPLE_CIPHER_SUITE_3
logging_level=DEBUG

**Output from s_client:**

openssl s_client -connect 127.0.0.1:5696 -cert /home/jzendle/pykmip/certs/client_certificate_john_doe.pem -key /home/jzendle/pykmip/certs/client_key_john_doe.pem -CAfile /home/jzendle/pykmip/certs/root_certificate.pem 
CONNECTED(00000003)
write:errno=0

no peer certificate available

No client certificate CA names sent

SSL handshake has read 0 bytes and written 283 bytes
Verification: OK

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)


**Server.log for same:**

2020-08-04 10:39:22,979 - kmip.server - INFO - Receiving incoming connection from: 127.0.0.1:37568
2020-08-04 10:39:22,979 - kmip.server - INFO - Dedicating session 00000001 to 127.0.0.1:37568
2020-08-04 10:39:22,980 - kmip.server.session.00000001 - INFO - Starting session: 00000001
2020-08-04 10:39:22,980 - kmip.server.session.00000001 - INFO - Failure running TLS handshake
2020-08-04 10:39:22,980 - kmip.server.session.00000001 - ERROR - [SSL] internal error (_ssl.c:1091)
Traceback (most recent call last):
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/services/server/session.py", line 102, in run
    self._connection.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1091)
2020-08-04 10:39:22,981 - kmip.server.session.00000001 - INFO - Stopping session: 00000001

**Running demo client gives same result:**

contents of ~/.pykmip/pykmip.conf

[client]
host=127.0.0.1
port=5696
keyfile=/home/jzendle/pykmip/certs/client_key_john_doe.pem
certfile=/home/jzendle/pykmip/certs/client_certificate_john_doe.pem
cert_reqs=CERT_REQUIRED
ssl_version=PROTOCOL_SSLv23
ca_certs=/home/jzendle/pykmip/certs/root_certificate.pem
**do_handshake_on_connect=True**
suppress_ragged_eofs=True
username=example_username
password=example_password

$ python create.py --algorithm AES -l 256
An error occurred while connecting to appliance 127.0.0.1: [Errno 0] Error
could not open client connection: [Errno 0] Error
Traceback (most recent call last):
  File "create.py", line 49, in <module>
    config_file=opts.config_file
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/pie/client.py", line 1745, in __enter__
    self.open()
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/pie/client.py", line 173, in open
    self.proxy.open()
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/services/kmip_client.py", line 285, in open
    six.reraise(*last_error)
  File "/home/jzendle/venv37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/services/kmip_client.py", line 274, in open
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python3.7/ssl.py", line 1172, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.7/ssl.py", line 1163, in _real_connect
    self.do_handshake()

setting client *do_handshake_on_connect=False** gives similar result

 python create.py --algorithm AES -l 256 
2020-08-04 10:50:10,895 - demo - ERROR - [Errno 0] Error

and server logs same error

2020-08-04 10:50:10,894 - kmip.server.session.00000002 - ERROR - [SSL] internal error (_ssl.c:1091)
Traceback (most recent call last):
  File "/home/jzendle/venv37/lib/python3.7/site-packages/kmip/services/server/session.py", line 102, in run
    self._connection.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1091)
2020-08-04 10:50:10,894 - kmip.server.session.00000002 - INFO - Stopping session: 00000002

**Comment by jzendle** [comment]
Hi Ken,

I punted on Ubuntu 20.0.4 with python 3.7 and spun up an Ubuntu 18.0.4 and used the stock python 3.6 and all is working as expected (yeah). I have updated the issue title to reflect that PyKMIP does not yet work with Ubuntu 20.0.4.

Thanks for the help!

**Comment by KBassford** [comment]
My hunch is that it's something not included.  I've used both Alpine and Devuan Linux platforms (both are really stripped down Debian Linux) with Python 3.7 (if memory severs me correct, I'm not in front of any of my boxes at the moment.  COVID-19 and all that.)  Don't forget to follow the directions listed here: [https://pykmip.readthedocs.io/en/latest/installation.html](url).  Everything must include the dev header libs or it will not work.  I always had to add those as they are never included in the base installation.  Hope that helps.

**Comment by jzendle** [comment]
Got sidetracked ... turns out openssl 1.1.1f has stopped supporting TLSv1 (good news)

I updated the configs accordingly and have working install.

working configs:

  [client]
host=127.0.0.1
port=5696
keyfile=/etc/pykmip/certs/client_key_john_doe.pem
certfile=/etc/pykmip/certs/client_certificate_john_doe.pem
cert_reqs=CERT_REQUIRED
**ssl_version=PROTOCOL_TLSv1_2**
ca_certs=/etc/pykmip/certs/root_certificate.pem
do_handshake_on_connect=True
suppress_ragged_eofs=True
username=example_username
password=example_password


[server]
hostname=0.0.0.0
port=5696
key_path=/etc/pykmip/certs/server_key.pem
certificate_path=/etc/pykmip/certs/server_certificate.pem
ca_path=/etc/pykmip/certs/root_certificate.pem
**auth_suite=TLS1.2**
policy_path=/etc/pykmip/policies
enable_tls_client_auth=True
tls_cipher_suites=
    TLS_RSA_WITH_AES_128_CBC_SHA256
    TLS_RSA_WITH_AES_256_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
logging_level=DEBUG
