### ISSUE TITLE
Need help with 

### ISSUE THREAD

**Issue by adaveGithub** [OpenKMIP/PyKMIP#655]
Hello All, 

I am hitting below error while trying to open connection. using __version__ = '0.8.0'

[2021-09-21 03:58:20,243] [host_kmip_client] [MainThread] [ERROR] [SSL] PEM lib (_ssl.c:2815)
Traceback (most recent call last):
  File "./host_kmip_client.py", line 85, in open_connection
    self.client.open()
  File "/usr/lib/python2.7/site-packages/kmip/pie/client.py", line 135, in open
    raise e
SSLError: [SSL] PEM lib (_ssl.c:2815)

I'm calling it using below function.
client.open()

**Comment by adaveGithub** [comment]
@PeterHamilton Can you help me here. I am stuck and no way to go to use this fabulous project PyKMIP. Here is the background

1) Register a client to GSKLM server. 
2) Generate a Peer_to_Peer device group/key and register wwpn 'Owner'
3) Create a 'partner' and pass the generated key.

Thanks in Advance for all help!

**Comment by adaveGithub** [comment]
Closing this issue.
