### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by Amn04** [OpenKMIP/PyKMIP#674]
I had started sever with ─`$ sudo pykmip-server` command
my server.conf file is :
`[server]
hostname=127.0.0.1
port=5696
certificate_path=/etc/pykmip/server_certificate.pem
key_path=/etc/pykmip/server_key.pem
ca_path=/etc/pykmip/root_certificate.pem
auth_suite=Basic
policy_path=/home/aman/PyKMIP/examples/
enable_tls_client_auth=True
tls_cipher_suites=
        TLS_RSA_WITH_AES_128_CBC_SHA256
        TLS_RSA_WITH_AES_256_CBC_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
logging_level=INFO
`

client command i used is - `[~/PyKMIP/kmip/demos/pie]
└─$ sudo python create.py  --algorithm=RC4 --length=128
`

pykmip.conf file is :
`[client]
host=127.0.0.1
port=5696
certfile=/etc/pykmip/client/client_certificate_jane_doe.pem
keyfile=/etc/pykmip/client/client_key_jane_doe.pem
ca_certs=/etc/pykmip/client/root_certificate.pem
cert_reqs=CERT_REQUIRED
ssl_version=PROTOCOL_SSLv23
do_handshake_on_connect=True
suppress_ragged_eofs=True
username=aman
password=aman`

output I got is - 
`An error occurred while connecting to appliance 127.0.0.1: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
could not open client connection: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
Traceback (most recent call last):
  File "/home/aman/PyKMIP/kmip/demos/pie/create.py", line 47, in <module>
    with client.ProxyKmipClient(
  File "/usr/lib/python3/dist-packages/kmip/pie/client.py", line 1745, in __enter__
    self.open()
  File "/usr/lib/python3/dist-packages/kmip/pie/client.py", line 173, in open
    self.proxy.open()
  File "/usr/lib/python3/dist-packages/kmip/services/kmip_client.py", line 285, in open
    six.reraise(*last_error)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/kmip/services/kmip_client.py", line 274, in open
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python3.10/ssl.py", line 1375, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.10/ssl.py", line 1366, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
`

**Comment by Amn04** [comment]
Issue solved. I was using kali Linux to use pykmip but when I switched to Ubuntu same configuration started working. 
So closing issue.
