### ISSUE TITLE
Error when trying to destroy an unrevoked key

### ISSUE THREAD

**Issue by grace-lytle** [OpenKMIP/PyKMIP#678]
When running TestProxyKmipClientIntegration any key that hasn't been revoked first can not be destroyed and the test fails

```
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/lombagr1/Dev/PyKMIP/kmip/tests/integration/services/test_proxykmipclient.py", line 108, in test_create_get_wrapped_destroy
    self.client.destroy(wrapping_id)
  File "/home/lombagr1/Dev/PyKMIP/kmip/pie/client.py", line 41, in wrapper
    return function(self, *args, **kwargs)
  File "/home/lombagr1/Dev/PyKMIP/kmip/pie/client.py", line 1193, in destroy
    raise exceptions.KmipOperationFailure(status, reason, message)
kmip.pie.exceptions.KmipOperationFailure: OPERATION_FAILED: PERMISSION_DENIED - Object is active and cannot be destroyed.
```

**Comment by MahmoudMansourr** [comment]
I think you need to to revoke the managed object(key) first before destroying it.
quote from the documentation "Activated objects must be revoked before they can be destroyed."
