### ISSUE TITLE
test_mac_with_cryptographic_failure fails

### ISSUE THREAD

**Issue by danigm** [OpenKMIP/PyKMIP#690]
This test is failing for me with the current master version in openSUSE Tumbleweed. I think it could be related to the openssl version, I've not found anything related to the python dependencies.

```
_____________________ TestCryptographyEngine.test_mac_with_cryptographic_failure _____________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/danigm/Projects/suse/tmp/PyKMIP/kmip/tests/unit/services/server/crypto/test_engine.py", line 252, in test_mac_with_cryptographic_failure
    self.assertRaises(
  File "/home/danigm/Projects/suse/tmp/PyKMIP/env/lib64/python3.10/site-packages/testtools/testcase.py", line 467, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/danigm/Projects/suse/tmp/PyKMIP/env/lib64/python3.10/site-packages/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method CryptographyEngine.mac of <kmip.services.server.crypto.engine.CryptographyEngine object at 0x7fdc04a0ff10>> returned b'\xe0\x9a\xf0\xb6lV\x83\xb2'
```

**Comment by arp102** [comment]
There was an issue with that test for some versions of the `cryptography` module, but it should be fixed since #702.
