### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by electrofloat** [OpenKMIP/PyKMIP#705]
I'm getting an error every time the client disconnects:

```
Exception in thread 00000001:
Traceback (most recent call last):
  File "/tmp/1/lib/python3.10/site-packages/kmip/services/server/session.py", line 117, in run
    self._connection.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python3.10/ssl.py", line 1313, in shutdown
    super().shutdown(how)
OSError: [Errno 107] Transport endpoint is not connected
```

Probably something like this is needed:
https://github.com/FreeOpcUa/python-opcua/pull/740/files

(https://github.com/FreeOpcUa/python-opcua/issues/739)

**Comment by eyooooo** [comment]
samesies. fresh install, using pykmip to play with kms on esxi

```
Exception in thread 00000015:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/PyKMIP-0.11.0.dev1-py3.10.egg/kmip/services/server/session.py", line 116, in run
    self._connection.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python3.10/ssl.py", line 1342, in shutdown
    super().shutdown(how)
OSError: [Errno 107] Transport endpoint is not connected
```
