### ISSUE TITLE
Self-Signed verification issue when using certificates on Windows with Python 3.8.6/3.7.9

### ISSUE THREAD

**Issue by pastadin** [OpenKMIP/PyKMIP#709]
Whenever I try to run a basic client against a server I get this:

```
An error occurred while connecting to appliance 127.0.0.1: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)
could not open client connection: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)
Traceback (most recent call last):
  File ".\client.py", line 13, in <module>
    client.open()
  File "C:\Users\pastadin\sandbox\pykmipping\pykmip-venv\lib\site-packages\kmip\pie\client.py", line 173, in open
    self.proxy.open()
  File "C:\Users\pastadin\sandbox\pykmipping\pykmip-venv\lib\site-packages\kmip\services\kmip_client.py", line 285, in open
    six.reraise(*last_error)
  File "C:\Users\pastadin\sandbox\pykmipping\pykmip-venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\pastadin\sandbox\pykmipping\pykmip-venv\lib\site-packages\kmip\services\kmip_client.py", line 274, in open
    self.socket.connect((self.host, self.port))
  File "C:\Users\pastadin\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1172, in connect
    self._real_connect(addr, False)
  File "C:\Users\pastadin\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1163, in _real_connect
    self.do_handshake()
  File "C:\Users\pastadin\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)
```

client.conf:

```
[client]
host=127.0.0.1
port=5696
keyfile=.\certs.create_script\client.key
certfile=.\certs.create_script\client.pem
ca_certs=..\server\certs.create_script\ca.pem
cert_reqs=CERT_REQUIRED
ssl_version=PROTOCOL_SSLv23
do_handshake_on_connect=True
suppress_ragged_eofs=True
username=example_username
password=example_password
```

client.py:
```
from kmip.pie import objects
from kmip.pie.client import ProxyKmipClient, enums

client = ProxyKmipClient(
    config_file="C:\\Users\\pastadin\\sandbox\\pykmipping\\client\\client.conf",
    config=None,
)

print("About to test connection")

client.open()
```

server.conf:
```
[server]
hostname=127.0.0.1
port=5696
certificate_path=.\certs.create_script\server.pem
key_path=.\certs.create_script\server.key
ca_path=.\certs.create_script\ca.pem
auth_suite=Basic
policy_path=.\policies
enable_tls_client_auth=False
tls_cipher_suites=
    EXAMPLE_CIPHER_SUITE_1
    EXAMPLE_CIPHER_SUITE_2
    EXAMPLE_CIPHER_SUITE_3
logging_level=INFO
database_path=.\server.db
```

This happens both with certificates generated via the `openssl` tool as well as those via the `bin/create_certificates.py` script (I have renamed them to server/client/ca with pem/key as the extension). From running openssl verify (in wsl after changing the line extensions) I can confirm that the server/client certs are signed by the ca key (again, both for the create_certificates and openssl).

s_client yields the following when I try to connect from wsl to windows:

```
 openssl s_client -connect 127.0.0.1:5696 -cert ./certs.create_script/client.pem -key ./certs.create_script/client.key -CAfile ../server/certs.create_script/ca.pem
80FB8F202F7F0000:error:8000006F:system library:BIO_connect:Connection refused:../crypto/bio/bio_sock2.c:125:calling connect()
80FB8F202F7F0000:error:10000067:BIO routines:BIO_connect:connect error:../crypto/bio/bio_sock2.c:127:
connect:errno=111
```

As this is a timeout I'm trying to stand the server up in wsl but I'm having difficulty downgrading python.

Having reviewed the other issue tickets, I'm at something of a loss of what to do about this - can you give me any pointers? :)

**Comment by pastadin** [comment]
Just to add an addendum, I've stood up the sever in WSL and had this back (isn't working in other words):

```openssl s_client -connect 127.0.0.1:5696 -cert ./certs.create_script/client.pem -key ./certs.create_script/client.key -CAfile ../server/certs.create_script/ca.pem
CONNECTED(00000003)
802B54D6447F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

**Comment by pastadin** [comment]
Turns out the self-signed issues were something of a red herring, the issue was actually that I had the `config` attribute set to `None`, I have since removed it and it works:


```from kmip.pie import objects
from kmip.pie.client import ProxyKmipClient, enums

client = ProxyKmipClient(
    config_file="./client.conf",

    # the offending line
    config=None, 
)
